### ISSUE TITLE
No subdomains returned anymore

### ISSUE THREAD

**Issue by cosad3s** [ARPSyndicate/puncia#10]
![image](https://github.com/user-attachments/assets/f1cf1407-e952-456c-a172-ce895137c2b9)

I am aware of that rule: *"To avoid abuse of this service, we have enforced aggressive rate-limits. During periods of high demand or extensive production, an empty list `[]` is returned. We do not take responsibility for any malicious use of our data, and such use is entirely unintended."* (https://www.subdomain.center/)

But since some time, I do not receive any subdomains anymore from Puncia.

Are there rules regarding limits for subdomains searches (API key, captcha ...) ?

**Comment by g147** [comment]
Hello Sébastien! 

We were working on migrating & scaling [Subdomain Center](https://www.subdomain.center) this month that's why you must have experienced some unusual downtimes. We migrated from AWS to OVH, enhanced the enumeration logic & added over a billion subdomains to the database. In coming months, we will be releasing more features like clustering subdomains not just domain-wise but also application-wise. 

Additionally, the rule is changed a little - _'To avoid abuse of this service, we have enforced aggressive rate-limits & a maximum of 500 subdomains per request sorted in a random order. During periods of high demand or extensive production, an empty list `[]` is returned. We do not take responsibility for any malicious use of our data, and such use is entirely unintended.'_ 

There are no captchas enforced but yes paid users do get an API key with which they get unrestricted access -https://www.arpsyndicate.io/pricing.html

Thanks for reaching out & feel free to ask if you have any additional queries.
